// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmpaerslpzkqilsuqbms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtcGFlcnNscHprcWlsc3VxYm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3Mjg0NDEsImV4cCI6MjA5MDMwNDQ0MX0.lFi7iNlBtpBe348TH3kwFkZwTcFvvmcpQqrQDZrBCxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});